# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualInputIn(object):
    def setupUi(self, ManualInputIn):
        ManualInputIn.setObjectName("ManualInputIn")
        ManualInputIn.resize(572, 148)
        self.centralwidget = QtWidgets.QWidget(ManualInputIn)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 0, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #4F90BD;")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 60, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(390, 60, 71, 31))
        self.save_button.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: #4F90BD;\n"
"    border: 1px solid #4F90BD;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4F90BD;\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.save_button.setObjectName("save_button")
        ManualInputIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ManualInputIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 26))
        self.menubar.setObjectName("menubar")
        ManualInputIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ManualInputIn)
        self.statusbar.setObjectName("statusbar")
        ManualInputIn.setStatusBar(self.statusbar)

        self.retranslateUi(ManualInputIn)
        QtCore.QMetaObject.connectSlotsByName(ManualInputIn)

    def retranslateUi(self, ManualInputIn):
        _translate = QtCore.QCoreApplication.translate
        ManualInputIn.setWindowTitle(_translate("ManualInputIn", "Manual In Input"))
        self.label_4.setText(_translate("ManualInputIn", "Masukkan nomor plat mobil"))
        self.save_button.setText(_translate("ManualInputIn", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualInputIn = QtWidgets.QMainWindow()
    ui = Ui_ManualInputIn()
    ui.setupUi(ManualInputIn)
    ManualInputIn.show()
    sys.exit(app.exec_())
